{% set name = "jaraco.functools" %}
{% set version = "4.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace(".", "_") }}-{{ version }}.tar.gz
  sha256: 880c577ec9720b3a052d5bc611fb9f2269b3d87902ef42440df443b88e443280

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - setuptools >=77
    - setuptools-scm >=3.4.1
    - toml
    - coherent.licensed
  # - coherent.licensed # Is listed in requirements, we don't have it in the registry
  run:
    - python
    - more-itertools
  run_constrained:
    - pytest-checkdocs >=2.14
    - pytest-enabler >=3.4

test:
  source_files:
    - test_functools.py
  imports:
    - jaraco.functools
  requires:
    - pip
    - pytest >=6,!= 8.1.*
    - jaraco.classes
  commands:
    - pip check
    - pytest -vv test_functools.py -k "not test_function_throttled"

about:
  home: https://github.com/jaraco/jaraco.functools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Additional functools in the spirit of stdlib's functools.
  doc_url: https://github.com/jaraco/jaraco.functools
  dev_url: https://github.com/jaraco/jaraco.functools

extra:
  recipe-maintainers:
    - carlodri
